import os

TWT_API_KEY = os.getenv('NEWSLYNX_TWT_API_KEY')
TWT_API_SECRET = os.getenv('NEWSLYNX_TWT_API_SECRET')
TWT_ACCESS_TOKEN = os.getenv('NEWSLYNX_TWT_ACCESS_TOKEN')
TWT_ACCESS_SECRET = os.getenv('NEWSLYNX_TWT_ACCESS_SECRET')