import unittest
import os
import pytz 
import datetime
from time import time
from birdfeeder.parsers import parse_tweet 
from birdfeeder import Stream 

TEST_DIR = os.path.abspath(os.path.dirname(__file__))
FIXTURES_DIR = os.path.join(TEST_DIR, 'fixtures')

class Tests(unittest.TestCase):
  
  def test_parse_tweet(self):

    raw1 = {'contributors': None, 'truncated': False, 'text': u"\U0001f346\U0001f346\U0001f346 of all the emojis why this one omg. you're sitting next to me. lol. hello", 'in_reply_to_status_id': None, 'id': 476936535623741440, 'favorite_count': 0, 'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>', 'retweeted': False, 'coordinates': {'type': 'Point', 'coordinates': [-77.436202, 39.36608]}, 'entities': {'user_mentions': [], 'symbols': [], 'trends': [], 'hashtags': [], 'urls': []}, 'in_reply_to_screen_name': None, 'id_str': '476936535623741440', 'retweet_count': 0, 'in_reply_to_user_id': None, 'favorited': False, 'user': {'follow_request_sent': None, 'profile_use_background_image': True, 'default_profile_image': False, 'id': 842531234, 'verified': False, 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/476868598447616000/F1dMmlug_normal.jpeg', 'profile_sidebar_fill_color': '95E8EC', 'profile_text_color': '3C3940', 'followers_count': 292, 'profile_sidebar_border_color': '5ED4DC', 'id_str': '842531234', 'profile_background_color': '0099B9', 'listed_count': 0, 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme4/bg.gif', 'utc_offset': None, 'statuses_count': 7450, 'description': "that's the thing about pain, it demands to be felt", 'friends_count': 915, 'location': u'', 'profile_link_color': '0099B9', 'profile_image_url': 'http://pbs.twimg.com/profile_images/476868598447616000/F1dMmlug_normal.jpeg', 'following': None, 'geo_enabled': True, 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/842531234/1402542760', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme4/bg.gif', 'name': 'katelyn marie', 'lang': 'en', 'profile_background_tile': False, 'favourites_count': 1185, 'screen_name': 'jazzytazzyyy', 'notifications': None, 'url': None, 'created_at': 'Sun Sep 23 22:46:29 +0000 2012', 'contributors_enabled': False, 'time_zone': None, 'protected': False, 'default_profile': False, 'is_translator': False}, 'geo': {'type': 'Point', 'coordinates': [39.36608, -77.436202]}, 'in_reply_to_user_id_str': None, 'possibly_sensitive': False, 'lang': 'en', 'created_at': 'Thu Jun 12 03:58:25 +0000 2014', 'filter_level': 'medium', 'in_reply_to_status_id_str': None, 'place': {'full_name': 'Ballenger Creek, MD', 'url': 'https://api.twitter.com/1.1/geo/id/be0e62c690c5acbc.json', 'country': 'United States', 'place_type': 'city', 'bounding_box': {'type': 'Polygon', 'coordinates': [[[-77.467661, 39.348755], [-77.467661, 39.3995183], [-77.409337, 39.3995183], [-77.409337, 39.348755]]]}, 'country_code': 'US', 'attributes': {}, 'id': 'be0e62c690c5acbc', 'name': 'Ballenger Creek'}}
    parse1 = {'text': "\xf0\x9f\x8d\x86\xf0\x9f\x8d\x86\xf0\x9f\x8d\x86 of all the emojis why this one omg. you're sitting next to me. lol. hello", 'img_urls': [], 'hashtags': [], 'datetime': datetime.datetime(2014, 6, 12, 3, 58, 25, tzinfo=pytz.utc), 'user_mentions': [], 'in_reply_to_status_id': None, 'verified': 0, 'screen_name': 'jazzytazzyyy', 'user_location': u'', 'twitter_id': '476936535623741440', 'in_reply_to_screen_name': None, 'urls': []}
    raw2 = {'contributors': None, 'truncated': False, 'text': '@fanypackk Hello cutie^_^ My name is Linda Chow. I am a Lolita from Hong Kong. Could we be friends for each other?', 'in_reply_to_status_id': None, 'id': 476936535594385409, 'favorite_count': 0, 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'retweeted': False, 'coordinates': None, 'entities': {'user_mentions': [{'id': 363763821, 'indices': [0, 10], 'id_str': '363763821', 'screen_name': 'fanypackk', 'name': 'Tiffany Hsu'}], 'symbols': [], 'trends': [], 'hashtags': [], 'urls': []}, 'in_reply_to_screen_name': 'fanypackk', 'id_str': '476936535594385409', 'retweet_count': 0, 'in_reply_to_user_id': 363763821, 'favorited': False, 'user': {'follow_request_sent': None, 'profile_use_background_image': True, 'default_profile_image': False, 'id': 435981919, 'verified': False, 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1847374879/short-sleeves-strawberry-lolita-op-dress-1-whm-01_1_normal.jpg', 'profile_sidebar_fill_color': 'E5507E', 'profile_text_color': '362720', 'followers_count': 607, 'profile_sidebar_border_color': 'CC3366', 'id_str': '435981919', 'profile_background_color': 'FF6699', 'listed_count': 1, 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme11/bg.gif', 'utc_offset': -28800, 'statuses_count': 3274, 'description': 'My Lolita Dress works to provide top quality cotton lolita clothes, lolita dresses, gothic lolita jumpers, etc, at low price.', 'friends_count': 1443, 'location': 'HK', 'profile_link_color': 'B40B43', 'profile_image_url': 'http://pbs.twimg.com/profile_images/1847374879/short-sleeves-strawberry-lolita-op-dress-1-whm-01_1_normal.jpg', 'following': None, 'geo_enabled': False, 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/435981919/1398663979', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme11/bg.gif', 'name': 'My Lolita Dress', 'lang': 'en', 'profile_background_tile': True, 'favourites_count': 1035, 'screen_name': 'MyLolitaDress', 'notifications': None, 'url': 'http://www.my-lolita-dress.com', 'created_at': 'Tue Dec 13 17:12:38 +0000 2011', 'contributors_enabled': False, 'time_zone': 'Alaska', 'protected': False, 'default_profile': False, 'is_translator': False}, 'geo': None, 'in_reply_to_user_id_str': '363763821', 'possibly_sensitive': False, 'lang': 'en', 'created_at': 'Thu Jun 12 03:58:25 +0000 2014', 'filter_level': 'medium', 'in_reply_to_status_id_str': None, 'place': None}
    parse2 = {'text': '@fanypackk Hello cutie^_^ My name is Linda Chow. I am a Lolita from Hong Kong. Could we be friends for each other?', 'img_urls': [], 'hashtags': [], 'datetime': datetime.datetime(2014, 6, 12, 3, 58, 25, tzinfo=pytz.utc), 'user_mentions': ['fanypackk'], 'in_reply_to_status_id': None, 'verified': 0, 'screen_name': 'MyLolitaDress', 'user_location': 'HK', 'twitter_id': '476936535594385409', 'in_reply_to_screen_name': 'fanypackk', 'urls': []}
    assert(parse_tweet(raw1) == parse1)
    assert(parse_tweet(raw2) == parse2)
